### PR TITLE
Validate hostnames

### PR DESCRIPTION
**Pull request by DanielOaks**
Just validates hostnames before setting them.

Validation code mostly taken from [here](http://stackoverflow.com/questions/2532053/validate-a-hostname-string) with another check to prevent empty strings from excepting.

### CODE REVIEW

**Comment by ghost** [comment]
This check _looks_ like it would exclude IPv6 addresses...

**Comment by DanielOaks** [comment]
Hmm, it should only be checking hostnames, and not IP addresses.

Is there anything special about hostnames with IPv6 that would make them
fail checks?

**Comment by ghost** [comment]
I can't think of anything that wouldn't signify a problem higher up on the system chain, but apparently I was a derpus when I commented last night so ignore me. Looks good otherwise, though.

**Comment by DanielOaks** [comment]
Aaron pointed out the validation wasn't being performed properly. We need to make sure it's under 253 due to the way that it counts octets, outlined [here](http://blogs.msdn.com/b/oldnewthing/archive/2012/04/12/10292868.aspx).

As an aside, could we directly get unicode from the rdns server that makes the character count 253 characters long in a Python string, but actually takes up more octets and should be invalid? (or would the way we get hostnames automagically convert it into punycode or something for us before we deal with it?)

**edit:** The regex we use would just reject those anyway, shouldn't be an issue for us.

**Comment by kaniini** [comment]
I would prefer it if we did not use regular expressions as they can be fairly slow in python.

**Pull request merged**
